var challenges = {
    "challenges": [
        "Ler um livro de um(a) autor(a) português",
        "Ler um livro de uma autora",
        "Ler um livro com mais de 500 páginas",
        "Ler um livro com menos de 200 páginas",
        "Ler um livro de um(a) autor(a) americano(a)",
        "Ler um livro de terror",
        "Ler um clássico",
        "Ler uma fantasia",
        "Ler um standalone",
        "Ler um livro de uma série",
        "Ler um livro de temática LGBTQIA+",
        "Ler um livro de um(a) autor(a) negro(a)",
        "Ler um livro de um(a) autor(a) espanhol(a)",
        "Ler um livro de um(a) autor(a) brasileiro(a)",
        "Ler um livro de um(a) autor(a) asiático(a)",
        "Ler uma distopia",
        "Ler um livro de ficção científica",
        "Ler um livro de não ficção",
        "Terminar uma série",
        "Ler um YA",
        "Ler um romance",
        "Ler a tua última compra",
        "Ler um livro oferecido",
        "Ler o teu género favorito",
        "Ler uma biografia",
        "Ler um livro escrito por uma pessoa famosa",
        "Ler um livro sobre o holocausto",
        "Ler um hotzão",
        "Ler um livro sobre saude mental",
        "Ler um livro com temática pesada",
        "Ler um livro do Stephen King",
        "Ler um livro de um(a) autor(a) de um país que gostavas de visitar",
        "Ler um livro com um animal na capa",
        "Ler um livro com flores na capa",
        "Ler um livro com um rosto na capa",
        "Ler um livro que tenha na capa a tua cor favorita",
        "Ler um livro com uma capa vermelha",
        "Ler um livro com a capa azul",
        "Ler um livro com a capa verde",
        "Ler um livro com a capa preta",
        "Ler um livro com a capa branca",
        "Ler um livro que tenha algo relacionado com o espaço na capa",
        "Ler um livro nomeado no GoodReads",
        "Ler um livro de um autor que ganhou o Nobel",
        "Ler um livro com a capa rosa",
        "Ler um livro com a capa roxa",
        "Ler um livro com a capa castanha",
        "Ler um livro que tens preguiça para ler",
        "Ler um livro de um(a) autor(a) que nunca leste",
        "Ler um livro desconhecido",
        "Ler o livro da tua TBR com a pior classificação do goodreads",
        "Ler o livro da tua TBR com a melhor classificação do goodreads",
        "Ler um livro com hype",
        "Ler um livro antigo da tua TBR",
        "Ler um livro que foi adaptado para cinema",
        "Ler um ebook",
        "Ler um livro que tenha um cão/gato como destaque",
        "Ler um livro que o título só tem uma palavra",
        "Ler um livro que tenha números no título",
        "Ler um livro que compraste pela capa",
        "Ler um manga",
        "Ler uma graphic novel",
        "Ler um livro que te intimida",
        "Ler um livro de um género fora da tua zona de conforto",
        "Ler um contemporâneo",
        "Ler um thriller",
        "Ler um livro de ficção adulta",
        "Ler um livro em inglês",
        "Ler um livro com a capa laranja",
        "Ler uma recomendação",
        "Ler um livro escolhido por alguém",
        "Ler um livro publicado em 2020",
        "Ler um livro publicado em 2021",
        "Ler um livro que foi publicado há mais de 10 anos",
        "Ler um livro do ano do teu nascimento",
        "Ler um paperback",
        "Ler um hardback",
        "Audiobook",
        "Ler um bestseller",
        "Ler um(a) autor(a) mais nova que tu",
        "Ler um livro de um(a) autor(a) que adores",
        "Ler um livro com uma capa feia",
        "Ler um livro que nunca achaste que ias ler",
        "Ler um livro que tenha uma cor no título",
        "Ler um livro adaptado para TV",
        "Ler um livro baseado em factos reais",
        "Ler um livro de um autor falecido",
        "Ler um livro que tenha o nome de alguém no título",
        "Ler um livro que tenha dragões",
        "Ler um livro que a magia exista",
        "Ler um livro que te custou menos de 15 euros",
        "Ler um livro que te custou mais de 15 euros",
        "Ler um livro com um título dificil de dizer",
        "Ler um livro que achas que te vai fazer chorar",
        "Ler um livro que tem uma criança como protagonista",
        "Ler um livro que tem um idoso como protagonista",
        "Ler um livro de um autor(a) nórdico",
        "Ler o terceiro livro da tua TBR atual",
        "Ler um livro que termine com páginas pares",
        "Ler um livro que termine com páginas impares",
        "Ler um livro com a capa vermelha",
        "Ler um livro escolhido por um familiar/amigo",
        "Ler um livro escolhido com os olhos tapados",
        "Ler um livro de um(a) autor(a) russo(a)",
        "Ler um livro encalhado",
        "Ler um livro que tenha uma festa",
        "Ler um livro de um(a) autor(a) inglês(a)",
        "Ler um livro de um(a) autor(a) americano(a)",
        "Ler um livro que a matemática seja abordada",
        "Ler um livro que se passe em ambiente de faculdade",
        "Ler um debut novel",
        "Ler um livro que o título+autor forme a palavra RICARDO",
        "Ler um livro que o título+autor forme a palavra MANGA",
        "Os teus seguidores do instagram, escolhem a tua leitura",
        "Ler um livro em português",
        "Ler um livro que compraste pela capa",
        "Ler um policial",
        "Ler um livro que o título+autor forme o teu nome",
        "Compra um liveo e lê",
        "Ler um livro que tem um lugar no título"
    ]
};
